export enum ActionTypes {
  DEVICES_HAS_ERRORED = 'DEVICES_HAS_ERRORED',
  DEVICES_IS_LOADING = 'DEVICES_IS_LOADING',
  DEVICES_FETCH_DATA_SUCCESS = 'DEVICES_FETCH_DATA_SUCCESS',
  DEVICES_SHOW_HIDE_CONFIRM_MODAL = 'DEVICES_SHOW_HIDE_CONFIRM_MODAL',
  DEVICES_ITEM_SELECTED = 'DEVICES_ITEM_SELECTED',

  VIEW_UPDATE = 'VIEW_UPDATE',

  DEVICE_FORM_IS_VALID = 'DEVICE_FORM_IS_VALID',
  DEVICE_NAME_IS_VALID = 'DEVICE_NAME_IS_VALID',
  DEVICE_ID_UPDATE = 'DEVICE_ID_UPDATE',
  DEVICE_NAME_UPDATE = 'DEVICE_NAME_UPDATE',
  DEVICE_DESCRIPTION_UPDATE = 'DEVICE_DESCRIPTION_UPDATE',
  DEVICE_FORM_IS_SAVED = 'DEVICE_FORM_IS_SAVED',

  DEVICE_FORM_HAS_ERRORED = 'DEVICE_FORM_HAS_ERRORED',
  DEVICE_FORM_IS_PENDING = 'DEVICE_FORM_IS_PENDING',
  DEVICE_FORM_POST_DATA_SUCCESS = 'DEVICE_FORM_POST_DATA_SUCCESS',
  DEVICE_FORM_PUT_DATA_SUCCESS = 'DEVICE_FORM_PUT_DATA_SUCCESS'
}
